declare module 'lucide-react' {
  import * as React from 'react';
  export type LucideIcon = React.ComponentType<any>;
  export type Icon = LucideIcon;

  const content: any;
  export default content;

  export const BarChart2: LucideIcon;
  export const Edit: LucideIcon;
  export const Trash: LucideIcon;
  export const Pencil: LucideIcon;
  export const Trash2: LucideIcon;
  export const UserCheck: LucideIcon;
  export const Scale: LucideIcon;

  export const ArrowLeft: LucideIcon;
  export const ScanLine: LucideIcon;
  export const Upload: LucideIcon;
  export const Loader2: LucideIcon;
  export const Plus: LucideIcon;
  export const Minus: LucideIcon;
  export const CheckCircle2: LucideIcon;
  export const Cpu: LucideIcon;
  export const Route: LucideIcon;
  export const Store: LucideIcon;
  export const AlertTriangle: LucideIcon;
  export const Info: LucideIcon;
  export const Coins: LucideIcon;
  export const ShieldCheck: LucideIcon;
  export const ShieldAlert: LucideIcon;
  export const Sparkles: LucideIcon;
  export const Calculator: LucideIcon;
  export const Eye: LucideIcon;
  export const Layers: LucideIcon;
  export const ChevronDown: LucideIcon;
  export const ChevronUp: LucideIcon;
  export const ClipboardList: LucideIcon;
  export const Package: LucideIcon;
  export const Home: LucideIcon;
  export const History: LucideIcon;
  export const User: LucideIcon;
  export const Users: LucideIcon;
  export const LogOut: LucideIcon;
  export const Check: LucideIcon;
  export const X: LucideIcon;
  export const Search: LucideIcon;
  export const Filter: LucideIcon;
  export const Download: LucideIcon;
  export const Calendar: LucideIcon;
  export const PieChart: LucideIcon;
  export const Award: LucideIcon;
  export const Building2: LucideIcon;
  export const DollarSign: LucideIcon;
  export const TrendingUp: LucideIcon;
  export const Lock: LucideIcon;
  export const FileText: LucideIcon;
  export const Wrench: LucideIcon;
  export const Battery: LucideIcon;
  export const Flame: LucideIcon;
  export const HelpCircle: LucideIcon;
  export const Recycle: LucideIcon;
  export const Box: LucideIcon;
  export const Clock: LucideIcon;
  export const Camera: LucideIcon;
  export const Truck: LucideIcon;
  export const LineChart: LucideIcon;
  export const ArrowRight: LucideIcon;
  export const Bike: LucideIcon;
  export const Leaf: LucideIcon;
  export const MapPin: LucideIcon;
  export const Phone: LucideIcon;
  export const MessageSquare: LucideIcon;
  export const Radio: LucideIcon;
  export const Navigation: LucideIcon;
  export const ChevronRight: LucideIcon;
  export const MessageCircle: LucideIcon;
  export const LayoutDashboard: LucideIcon;
  export const CheckSquare: LucideIcon;
  export const Tags: LucideIcon;
  export const LogIn: LucideIcon;
  export const RefreshCw: LucideIcon;
  export const XCircle: LucideIcon;
}
